#!/usr/bin/env python3
"""
ONLYSTATS ablation: replace QuGen with exhaustive (B, M) enumeration from schema.

As described in the paper (Section ablation): "ONLYSTATS, replacing the QUGEN module
with a purely statistics based card generation module, to assess the autonomous
performance of ISGEN."

Cards are generated by enumerating all valid (breakdown, measure) pairs from the
column profile. IsGen then runs unchanged.

Usage:
  python run_onlystats.py \\
    --csv data/Adidas_cleaned.csv \\
    --profile baseline/auto_eda_agent/output_adidas/step1_profiling/profile.json \\
    --output onlystats_output_adidas/insights_summary.json \\
    --cards-output onlystats_output_adidas/insight_cards.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from quis.shared.data_loader import load_data
from quis.isgen.pipeline import ISGENPipeline, ISGENConfig

_CATEGORICAL_CLASSES = {"Categorical"}
_TEMPORAL_CLASSES = {"Temporal"}
_NUMERICAL_CLASSES = {"Numerical"}
_AGGREGATIONS = ["SUM", "MEAN"]


def generate_cards_from_profile(df, profile_path: str) -> list[dict]:
    """
    Enumerate all valid (breakdown, measure) pairs from profile.json.
    Breakdowns: Categorical + Temporal columns (ID excluded — not meaningful as grouping dim).
    Measures: SUM and MEAN over all Numerical columns.
    """
    with open(profile_path, "r", encoding="utf-8") as f:
        profile = json.load(f)

    col_info = profile.get("columns", {})
    breakdowns: list[str] = []
    numerical_cols: list[str] = []

    for col_name, info in col_info.items():
        cls = info.get("data_type_class", "")
        if col_name not in df.columns:
            continue
        if cls in _CATEGORICAL_CLASSES or cls in _TEMPORAL_CLASSES:
            breakdowns.append(col_name)
        elif cls in _NUMERICAL_CLASSES:
            numerical_cols.append(col_name)

    cards: list[dict] = []
    seen: set[tuple] = set()
    for b_col in breakdowns:
        for m_col in numerical_cols:
            for agg in _AGGREGATIONS:
                measure_expr = f"{agg}({m_col})"
                key = (b_col, measure_expr)
                if key in seen:
                    continue
                seen.add(key)
                cards.append({
                    "question": f"How does {measure_expr} vary by {b_col}?",
                    "reason": f"Statistics-based analysis: {measure_expr} grouped by {b_col}.",
                    "breakdown": b_col,
                    "measure": measure_expr,
                })

    print(f"Generated {len(cards)} insight cards: "
          f"{len(breakdowns)} breakdowns × {len(numerical_cols)} measures × {len(_AGGREGATIONS)} aggs")
    print(f"  Breakdowns : {breakdowns}")
    print(f"  Measures   : {numerical_cols}")
    return cards


def main():
    parser = argparse.ArgumentParser(
        description="ONLYSTATS ablation: exhaustive (B,M) enumeration → IsGen"
    )
    parser.add_argument("--csv", required=True, help="Path to CSV dataset")
    parser.add_argument("--profile", required=True, help="Path to profile.json (column classifications)")
    parser.add_argument("--output", default="onlystats_output_adidas/insights_summary.json",
                        help="Output insights JSON path")
    parser.add_argument("--cards-output", default=None,
                        help="Optional: save generated insight cards JSON")
    parser.add_argument("--plot-dir", default=None, help="Directory to save plots")
    parser.add_argument("--beam-width", type=int, default=20)
    parser.add_argument("--exp-factor", type=int, default=20)
    parser.add_argument("--max-depth", type=int, default=1)
    parser.add_argument("--no-subspace", action="store_true", help="Skip subspace search")
    parser.add_argument("--max-overall-per-key", type=int, default=1)
    parser.add_argument("--max-subspace-per-key", type=int, default=2)
    parser.add_argument("--max-insights-per-question", type=int, default=2)
    args = parser.parse_args()

    if not os.path.isfile(args.csv):
        print(f"CSV not found: {args.csv}", file=sys.stderr)
        sys.exit(1)
    if not os.path.isfile(args.profile):
        print(f"Profile not found: {args.profile}", file=sys.stderr)
        sys.exit(1)

    df = load_data(args.csv)
    cards = generate_cards_from_profile(df, args.profile)

    if args.cards_output:
        os.makedirs(os.path.dirname(os.path.abspath(args.cards_output)), exist_ok=True)
        with open(args.cards_output, "w", encoding="utf-8") as f:
            json.dump(cards, f, indent=2, ensure_ascii=False)
        print(f"Saved {len(cards)} cards → {args.cards_output}")

    config = ISGENConfig(
        beam_width=args.beam_width,
        exp_factor=args.exp_factor,
        max_depth=args.max_depth,
        run_subspace_search=not args.no_subspace,
        plot_dir=args.plot_dir,
        max_overall_per_key=args.max_overall_per_key,
        max_subspace_per_key=args.max_subspace_per_key,
        max_insights_per_question=args.max_insights_per_question,
    )

    if config.run_subspace_search and not os.getenv("OPENAI_API_KEY") and not os.getenv("OPENAI_API_BASE"):
        parser.error("OPENAI_API_KEY (or OPENAI_API_BASE) required for subspace search.")

    llm = None
    if config.run_subspace_search:
        try:
            import importlib.util
            spec = importlib.util.spec_from_file_location(
                "llm_client",
                os.path.join(os.path.dirname(__file__), "quis", "qugen", "llm_client.py")
            )
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            llm = mod.get_default_llm_client(use_mock=False)
        except Exception as e:
            print(f"Warning: LLM client unavailable ({e}), running subspace search without LLM guidance.")

    pipeline = ISGENPipeline(config=config, llm_client=llm)
    summary = pipeline.run(df, cards, output_dir=args.plot_dir)

    out_dir = os.path.dirname(os.path.abspath(args.output))
    os.makedirs(out_dir, exist_ok=True)
    out_data = [
        {
            "question": s.get("question", ""),
            "explanation": s.get("explanation", ""),
            "plot_path": s.get("plot_path"),
            "insight": s.get("insight", {}),
        }
        for s in summary
    ]
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(out_data, f, indent=2, ensure_ascii=False)
    print(f"\nWrote {len(out_data)} insights → {args.output}")


if __name__ == "__main__":
    main()
