#!/usr/bin/env python3
"""
ONLYSTATS ablation: replace QuGen with exhaustive (B, M) enumeration from schema.

As described in the paper (Section ablation): "ONLYSTATS, replacing the QUGEN module
with a purely statistics based card generation module, to assess the autonomous
performance of ISGEN."

Cards are generated by enumerating all valid (breakdown, measure) pairs from the
column profile. IsGen then runs unchanged.

Usage:
  python run_onlystats.py \\
    --csv data/adidas_cleaned.csv \\
    --profile baseline/auto_eda_agent/output_adidas/step1_profiling/profile.json \\
    --suffix v4
Outputs: onlystats_results/onlystats_{yyyymmdd_hhiiss}_{dataset}_{suffix}/insights_summary.json,
         timing.json, usage.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from quis.shared.data_loader import load_data
from quis.isgen.pipeline import ISGENPipeline, ISGENConfig

_CATEGORICAL_CLASSES = {"Categorical"}
_TEMPORAL_CLASSES = {"Temporal"}
_NUMERICAL_CLASSES = {"Numerical"}
_AGGREGATIONS = ["SUM", "MEAN"]


def create_output_dir(csv_path: str, suffix: str, base_dir: str = "onlystats_results") -> Path:
    """Create timestamped output directory: {base_dir}/onlystats_{yyyymmdd_hhiiss}_{dataset}_{suffix}"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    dataset_name = Path(csv_path).stem
    dir_name = f"onlystats_{timestamp}_{dataset_name}_{suffix}"
    output_dir = Path(base_dir) / dir_name
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def save_timing_json(output_dir: Path, total_time: float, insights_generated: int, 
                     system: str = "onlystats") -> Path:
    """Save timing.json in format compatible with evaluation/metrics/time_to_insight.py"""
    throughput = insights_generated / total_time if total_time > 0 else 0
    
    timing_data = {
        system: {
            "total_time_seconds": total_time,
            "insights_generated": insights_generated,
            "throughput_insights_per_second": throughput,
            "step_times": {
                "card_generation": 0,  # ONLYSTATS doesn't have separate card generation step
                "isgen": total_time
            }
        }
    }
    
    timing_path = output_dir / "timing.json"
    with open(timing_path, 'w', encoding='utf-8') as f:
        json.dump(timing_data, f, indent=2)
    return timing_path


def save_usage_json(output_dir: Path, system: str = "onlystats") -> Path:
    """Save usage.json in format compatible with evaluation/metrics/token_usage.py"""
    # ONLYSTATS doesn't use LLM, so token usage is 0
    usage_data = {
        system: {
            "total": {
                "total_tokens": 0,
                "input_tokens": 0,
                "output_tokens": 0,
                "requests": 0,
                "model": "none"
            }
        }
    }
    
    usage_path = output_dir / "usage.json"
    with open(usage_path, 'w', encoding='utf-8') as f:
        json.dump(usage_data, f, indent=2)
    return usage_path


def generate_cards_from_profile(df, profile_path: str) -> list[dict]:
    """
    Enumerate all valid (breakdown, measure) pairs from profile.json.
    Breakdowns: Categorical + Temporal columns (ID excluded — not meaningful as grouping dim).
    Measures: SUM and MEAN over all Numerical columns.
    """
    with open(profile_path, "r", encoding="utf-8") as f:
        profile = json.load(f)

    col_info = profile.get("columns", {})
    breakdowns: list[str] = []
    numerical_cols: list[str] = []

    for col_name, info in col_info.items():
        cls = info.get("data_type_class", "")
        if col_name not in df.columns:
            continue
        if cls in _CATEGORICAL_CLASSES or cls in _TEMPORAL_CLASSES:
            breakdowns.append(col_name)
        elif cls in _NUMERICAL_CLASSES:
            numerical_cols.append(col_name)

    cards: list[dict] = []
    seen: set[tuple] = set()
    for b_col in breakdowns:
        for m_col in numerical_cols:
            for agg in _AGGREGATIONS:
                measure_expr = f"{agg}({m_col})"
                key = (b_col, measure_expr)
                if key in seen:
                    continue
                seen.add(key)
                cards.append({
                    "question": f"How does {measure_expr} vary by {b_col}?",
                    "reason": f"Statistics-based analysis: {measure_expr} grouped by {b_col}.",
                    "breakdown": b_col,
                    "measure": measure_expr,
                })

    print(f"Generated {len(cards)} insight cards: "
          f"{len(breakdowns)} breakdowns × {len(numerical_cols)} measures × {len(_AGGREGATIONS)} aggs")
    print(f"  Breakdowns : {breakdowns}")
    print(f"  Measures   : {numerical_cols}")
    return cards


def main():
    parser = argparse.ArgumentParser(
        description="ONLYSTATS ablation: exhaustive (B,M) enumeration → IsGen"
    )
    parser.add_argument("--csv", required=True, help="Path to CSV dataset")
    parser.add_argument("--profile", required=True, help="Path to profile.json (column classifications)")
    parser.add_argument("--suffix", default="v4", help="Output directory suffix, e.g. v4")
    parser.add_argument("--plot-dir", default=None, help="Directory to save plots")
    parser.add_argument("--beam-width", type=int, default=20)
    parser.add_argument("--exp-factor", type=int, default=20)
    parser.add_argument("--max-depth", type=int, default=1)
    parser.add_argument("--no-subspace", action="store_true", help="Skip subspace search")
    parser.add_argument("--max-overall-per-key", type=int, default=1)
    parser.add_argument("--max-subspace-per-key", type=int, default=2)
    parser.add_argument("--max-insights-per-question", type=int, default=2)
    args = parser.parse_args()

    if not os.path.isfile(args.csv):
        print(f"CSV not found: {args.csv}", file=sys.stderr)
        sys.exit(1)
    if not os.path.isfile(args.profile):
        print(f"Profile not found: {args.profile}", file=sys.stderr)
        sys.exit(1)

    # Create timestamped output directory
    output_dir = create_output_dir(args.csv, args.suffix)
    print(f"Output directory: {output_dir}")

    df = load_data(args.csv)
    cards = generate_cards_from_profile(df, args.profile)

    # Save insight cards
    cards_path = output_dir / "insight_cards.json"
    with open(cards_path, "w", encoding="utf-8") as f:
        json.dump(cards, f, indent=2, ensure_ascii=False)
    print(f"Saved {len(cards)} cards → {cards_path.name}")

    config = ISGENConfig(
        beam_width=args.beam_width,
        exp_factor=args.exp_factor,
        max_depth=args.max_depth,
        run_subspace_search=not args.no_subspace,
        plot_dir=args.plot_dir,
        max_overall_per_key=args.max_overall_per_key,
        max_subspace_per_key=args.max_subspace_per_key,
        max_insights_per_question=args.max_insights_per_question,
    )

    if config.run_subspace_search and not os.getenv("OPENAI_API_KEY") and not os.getenv("OPENAI_API_BASE"):
        parser.error("OPENAI_API_KEY (or OPENAI_API_BASE) required for subspace search.")

    llm = None
    if config.run_subspace_search:
        try:
            import importlib.util
            spec = importlib.util.spec_from_file_location(
                "llm_client",
                os.path.join(os.path.dirname(__file__), "quis", "qugen", "llm_client.py")
            )
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            llm = mod.get_default_llm_client(use_mock=False)
        except Exception as e:
            print(f"Warning: LLM client unavailable ({e}), running subspace search without LLM guidance.")

    t0 = time.perf_counter()
    pipeline = ISGENPipeline(config=config, llm_client=llm)
    summary = pipeline.run(df, cards, output_dir=args.plot_dir)
    t1 = time.perf_counter()
    total_time = t1 - t0

    # Save insights summary
    summary_path = output_dir / "insights_summary.json"
    out_data = [
        {
            "question": s.get("question", ""),
            "explanation": s.get("explanation", ""),
            "plot_path": s.get("plot_path"),
            "insight": s.get("insight", {}),
        }
        for s in summary
    ]
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(out_data, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(out_data)} insights → {summary_path.name}")

    # Save timing.json in evaluation-compatible format
    timing_path = save_timing_json(output_dir, total_time, len(out_data), system="onlystats")
    print(f"Saved timing: {timing_path.name}")

    # Save usage.json in evaluation-compatible format
    usage_path = save_usage_json(output_dir, system="onlystats")
    print(f"Saved usage: {usage_path.name}")

    print(f"\n{'='*70}")
    print("ONLYSTATS Pipeline Summary")
    print(f"{'='*70}")
    print(f"CSV: {args.csv}")
    print(f"Profile: {args.profile}")
    print(f"\nWall-clock seconds: {total_time:.3f}")
    print(f"\nInsights generated: {len(out_data)}")
    print(f"\nOutputs:")
    print(f"  {cards_path.name}")
    print(f"  {summary_path.name}")
    print(f"  {timing_path.name}")
    print(f"  {usage_path.name}")
    print(f"{'='*70}\n")


if __name__ == "__main__":
    main()
